version: '3'

networks:
  knotApi:

services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8088:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - knotApi
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - knotApi
  composer:
    image: composer:latest
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - knotApi
